// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Shop.DB.Context;

#nullable disable

namespace Shop.DB.Migrations
{
    [DbContext(typeof(MyShopDbContext))]
    partial class MyShopDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Shop.DB.Entities.Carts.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_Carts_UserId");

                    b.ToTable("Carts", (string)null);
                });

            modelBuilder.Entity("Shop.DB.Entities.Carts.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("integer")
                        .HasColumnName("CartId");

                    b.Property<int>("ProductVariantId")
                        .HasColumnType("integer")
                        .HasColumnName("ProductVariantId");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("Quantity");

                    b.HasKey("Id");

                    b.HasIndex("ProductVariantId")
                        .HasDatabaseName("IX_CartItems_ProductVariantId");

                    b.HasIndex("CartId", "ProductVariantId")
                        .IsUnique()
                        .HasDatabaseName("IX_CartItems_CartId_ProductVariantId");

                    b.ToTable("CartItems", null, t =>
                        {
                            t.HasCheckConstraint("CK_CartItem_Quantity", "\"Quantity\" > 0");
                        });
                });

            modelBuilder.Entity("Shop.DB.Entities.Catalog.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Name");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("ParentCategoryId");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId", "Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Categories_ParentCategoryId_Name");

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("Shop.DB.Entities.Catalog.Products.Attributes.ProductAttribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_ProductAttributes_Name");

                    b.ToTable("ProductAttributes", (string)null);
                });

            modelBuilder.Entity("Shop.DB.Entities.Catalog.Products.Attributes.ProductAttributeLink", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("ProductId");

                    b.Property<int>("ProductAttributeValueId")
                        .HasColumnType("integer")
                        .HasColumnName("ProductAttributeValueId");

                    b.HasKey("ProductId", "ProductAttributeValueId");

                    b.HasIndex("ProductAttributeValueId")
                        .HasDatabaseName("IX_ProductAttributeLinks_ProductAttributeValueId");

                    b.ToTable("ProductAttributeLinks", (string)null);
                });

            modelBuilder.Entity("Shop.DB.Entities.Catalog.Products.Attributes.ProductAttributeValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductAttributeId")
                        .HasColumnType("integer")
                        .HasColumnName("ProductAttributeId");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Value");

                    b.HasKey("Id");

                    b.HasIndex("ProductAttributeId", "Value")
                        .IsUnique()
                        .HasDatabaseName("IX_ProductAttributeValues_ProductAttributeId_Value");

                    b.ToTable("ProductAttributeValues", (string)null);
                });

            modelBuilder.Entity("Shop.DB.Entities.Catalog.Products.Images.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("ProductId");

                    b.Property<int?>("ProductOptionValueId")
                        .HasColumnType("integer")
                        .HasColumnName("ProductOptionValueId");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("SortOrder");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Url");

                    b.HasKey("Id");

                    b.HasIndex("ProductOptionValueId")
                        .HasDatabaseName("IX_ProductImages_ProductOptionValueId");

                    b.HasIndex("ProductId", "SortOrder")
                        .IsUnique()
                        .HasDatabaseName("IX_ProductImages_ProductId_SortOrder")
                        .HasFilter("\"ProductOptionValueId\" IS NULL");

                    b.HasIndex("ProductId", "Url")
                        .IsUnique()
                        .HasDatabaseName("IX_ProductImages_ProductId_Url");

                    b.HasIndex("ProductId", "ProductOptionValueId", "SortOrder")
                        .IsUnique()
                        .HasDatabaseName("IX_ProductImages_ProductId_ProductOptionValueId_SortOrder");

                    b.ToTable("ProductImages", null, t =>
                        {
                            t.HasCheckConstraint("CK_ProductImage_SortOrder", "\"SortOrder\" >= 0");
                        });
                });

            modelBuilder.Entity("Shop.DB.Entities.Catalog.Products.Options.ProductOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_ProductOptions_Name");

                    b.ToTable("ProductOptions", (string)null);
                });

            modelBuilder.Entity("Shop.DB.Entities.Catalog.Products.Options.ProductOptionLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("ProductId");

                    b.Property<int>("ProductOptionValueId")
                        .HasColumnType("integer")
                        .HasColumnName("ProductOptionValueId");

                    b.HasKey("Id");

                    b.HasIndex("ProductOptionValueId")
                        .HasDatabaseName("IX_ProductOptionLinks_ProductOptionValueId");

                    b.HasIndex("ProductId", "ProductOptionValueId")
                        .IsUnique()
                        .HasDatabaseName("IX_ProductOptionLinks_ProductId_ProductOptionValueId");

                    b.ToTable("ProductOptionLinks", (string)null);
                });

            modelBuilder.Entity("Shop.DB.Entities.Catalog.Products.Options.ProductOptionValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorHex")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("ColorHex");

                    b.Property<int>("ProductOptionId")
                        .HasColumnType("integer")
                        .HasColumnName("ProductOptionId");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("SortOrder");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Value");

                    b.HasKey("Id");

                    b.HasIndex("ProductOptionId", "Value")
                        .IsUnique()
                        .HasDatabaseName("IX_ProductOptionValues_ProductOptionId_Value");

                    b.ToTable("ProductOptionValues", (string)null);
                });

            modelBuilder.Entity("Shop.DB.Entities.Catalog.Products.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CatalogVariantId")
                        .HasColumnType("integer")
                        .HasColumnName("CatalogVariantId");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("CategoryId");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("Description");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("IsArchived");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("CatalogVariantId")
                        .HasDatabaseName("IX_Products_CatalogVariantId");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("IX_Products_CategoryId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Products_Name");

                    b.HasIndex("IsArchived", "CategoryId")
                        .HasDatabaseName("IX_Products_IsArchived_CategoryId");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("Shop.DB.Entities.Catalog.Products.ProductVariant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("Price");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("ProductId");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("StockQuantity");

                    b.Property<string>("VariantKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("VariantKey");

                    b.HasKey("Id");

                    b.HasIndex("StockQuantity")
                        .HasDatabaseName("IX_ProductVariants_StockQuantity_InStock")
                        .HasFilter("\"StockQuantity\" > 0");

                    b.HasIndex("ProductId", "VariantKey")
                        .IsUnique()
                        .HasDatabaseName("IX_ProductVariants_ProductId_VariantKey");

                    b.ToTable("ProductVariants", null, t =>
                        {
                            t.HasCheckConstraint("CK_ProductVariant_Price", "\"Price\" > 0");

                            t.HasCheckConstraint("CK_ProductVariant_StockQuantity", "\"StockQuantity\" >= 0");
                        });
                });

            modelBuilder.Entity("Shop.DB.Entities.Catalog.Products.VariantOptionLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductOptionId")
                        .HasColumnType("integer")
                        .HasColumnName("ProductOptionId");

                    b.Property<int>("ProductOptionLinkId")
                        .HasColumnType("integer")
                        .HasColumnName("ProductOptionLinkId");

                    b.Property<int?>("ProductOptionValueId")
                        .HasColumnType("integer")
                        .HasColumnName("ProductOptionValueId");

                    b.Property<int>("ProductVariantId")
                        .HasColumnType("integer")
                        .HasColumnName("ProductVariantId");

                    b.HasKey("Id");

                    b.HasIndex("ProductOptionLinkId")
                        .HasDatabaseName("IX_VariantOptionLinks_ProductOptionLinkId");

                    b.HasIndex("ProductOptionValueId")
                        .HasDatabaseName("IX_VariantOptionLinks_ProductOptionValueId");

                    b.HasIndex("ProductVariantId", "ProductOptionId")
                        .IsUnique()
                        .HasDatabaseName("IX_VariantOptionLinks_ProductVariantId_ProductOptionId");

                    b.HasIndex("ProductVariantId", "ProductOptionLinkId")
                        .IsUnique()
                        .HasDatabaseName("IX_VariantOptionLinks_ProductVariantId_ProductOptionLinkId");

                    b.ToTable("VariantOptionLinks", (string)null);
                });

            modelBuilder.Entity("Shop.DB.Entities.Discounts.Discount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("CategoryId");

                    b.Property<DateTimeOffset?>("EndAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("EndAt");

                    b.Property<int>("Form")
                        .HasColumnType("integer")
                        .HasColumnName("Form");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("IsActive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Name");

                    b.Property<int?>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("ProductId");

                    b.Property<int?>("ProductVariantId")
                        .HasColumnType("integer")
                        .HasColumnName("ProductVariantId");

                    b.Property<DateTimeOffset?>("StartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("StartAt");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer")
                        .HasColumnName("TypeId");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric")
                        .HasColumnName("Value");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("IX_Discounts_CategoryId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Discounts_Name");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("IX_Discounts_ProductId");

                    b.HasIndex("ProductVariantId")
                        .HasDatabaseName("IX_Discounts_ProductVariantId");

                    b.HasIndex("TypeId")
                        .HasDatabaseName("IX_Discounts_TypeId");

                    b.HasIndex("IsActive", "StartAt", "EndAt")
                        .HasDatabaseName("IX_Discounts_IsActive_StartAt_EndAt");

                    b.ToTable("Discounts", null, t =>
                        {
                            t.HasCheckConstraint("CK_Discount_Date", "(\"StartAt\" IS NULL) OR (\"EndAt\" IS NULL) OR (\"StartAt\" <= \"EndAt\")");

                            t.HasCheckConstraint("CK_Discount_Value", "\"Value\" > 0");
                        });
                });

            modelBuilder.Entity("Shop.DB.Entities.Discounts.DiscountProduct", b =>
                {
                    b.Property<int>("DiscountId")
                        .HasColumnType("integer")
                        .HasColumnName("DiscountId");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("ProductId");

                    b.HasKey("DiscountId", "ProductId");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("IX_DiscountProducts_ProductId");

                    b.ToTable("DiscountProducts", (string)null);
                });

            modelBuilder.Entity("Shop.DB.Entities.Discounts.DiscountType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_DiscountTypes_Name");

                    b.ToTable("DiscountTypes", (string)null);
                });

            modelBuilder.Entity("Shop.DB.Entities.Identity.CustomerProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasColumnName("City");

                    b.Property<string>("Country")
                        .HasColumnType("text")
                        .HasColumnName("Country");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("PhoneNumber");

                    b.Property<string>("PostalCode")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("PostalCode");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_CustomerProfiles_UserId");

                    b.ToTable("CustomerProfiles", (string)null);
                });

            modelBuilder.Entity("Shop.DB.Entities.Identity.PersonnelProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Department")
                        .HasColumnType("text")
                        .HasColumnName("Department");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("PhoneNumber");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_PersonnelProfiles_UserId");

                    b.ToTable("PersonnelProfiles", (string)null);
                });

            modelBuilder.Entity("Shop.DB.Entities.Identity.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Roles_Name");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Shop.DB.Entities.Identity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BlockReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("BlockReason");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Email");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("boolean")
                        .HasColumnName("IsBlocked");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("PasswordHash");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("RoleId");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Email");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("IX_Users_RoleId");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Username");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Shop.DB.Entities.Orders.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("")
                        .HasColumnName("CustomerEmail");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("")
                        .HasColumnName("CustomerName");

                    b.Property<string>("CustomerPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("CustomerPhone");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("PostalCode");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasDefaultValue("")
                        .HasColumnName("ShippingAddress");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("Status");

                    b.Property<string>("StripePaymentIntentId")
                        .HasColumnType("text")
                        .HasColumnName("StripePaymentIntentId");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("TotalAmount");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("StripePaymentIntentId")
                        .HasDatabaseName("IX_Orders_StripePaymentIntentId")
                        .HasFilter("\"StripePaymentIntentId\" IS NOT NULL");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Orders_UserId");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("IX_Orders_Status_CreatedAt");

                    b.ToTable("Orders", null, t =>
                        {
                            t.HasCheckConstraint("CK_Order_TotalAmount", "\"TotalAmount\" >= 0");
                        });
                });

            modelBuilder.Entity("Shop.DB.Entities.Orders.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("integer")
                        .HasColumnName("OrderId");

                    b.Property<decimal?>("OriginalPrice")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("OriginalPrice");

                    b.Property<int>("ProductVariantId")
                        .HasColumnType("integer")
                        .HasColumnName("ProductVariantId");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("Quantity");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("UnitPrice");

                    b.HasKey("Id");

                    b.HasIndex("ProductVariantId")
                        .HasDatabaseName("IX_OrderItems_ProductVariantId");

                    b.HasIndex("OrderId", "ProductVariantId")
                        .IsUnique()
                        .HasDatabaseName("IX_OrderItems_OrderId_ProductVariantId");

                    b.ToTable("OrderItems", null, t =>
                        {
                            t.HasCheckConstraint("CK_OrderItem_Quantity", "\"Quantity\" > 0");
                        });
                });

            modelBuilder.Entity("Shop.DB.Entities.Payments.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("Amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("varchar(3)")
                        .HasColumnName("Currency");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer")
                        .HasColumnName("OrderId");

                    b.Property<int?>("ProviderId")
                        .HasColumnType("integer")
                        .HasColumnName("ProviderId");

                    b.Property<string>("ProviderPaymentId")
                        .HasColumnType("text")
                        .HasColumnName("ProviderPaymentId");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("Status");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("IX_Payments_OrderId");

                    b.HasIndex("ProviderId")
                        .HasDatabaseName("IX_Payments_ProviderId");

                    b.ToTable("Payments", null, t =>
                        {
                            t.HasCheckConstraint("CK_Payment_Amount", "\"Amount\" > 0");

                            t.HasCheckConstraint("CK_Payment_Currency", "LENGTH(\"Currency\") = 3");
                        });
                });

            modelBuilder.Entity("Shop.DB.Entities.Payments.Provider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Providers_Name");

                    b.ToTable("Providers", (string)null);
                });

            modelBuilder.Entity("Shop.DB.Entities.Reviews.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("Comment");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean")
                        .HasColumnName("IsApproved");

                    b.Property<int?>("OrderId")
                        .HasColumnType("integer")
                        .HasColumnName("OrderId");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("ProductId");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("Rating");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("IX_Reviews_OrderId");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("IX_Reviews_ProductId");

                    b.HasIndex("UserId", "ProductId")
                        .IsUnique()
                        .HasDatabaseName("IX_Reviews_UserId_ProductId");

                    b.HasIndex("ProductId", "IsApproved", "CreatedAt")
                        .HasDatabaseName("IX_Reviews_ProductId_IsApproved_CreatedAt");

                    b.ToTable("Reviews", null, t =>
                        {
                            t.HasCheckConstraint("CK_Review_Rating", "\"Rating\" >= 1 AND \"Rating\" <= 5");
                        });
                });

            modelBuilder.Entity("Shop.DB.Entities.Support.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("IsRead");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("Message");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("Type");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("Url");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Notifications_UserId");

                    b.HasIndex("UserId", "IsRead", "CreatedAt")
                        .HasDatabaseName("IX_Notifications_UserId_IsRead_CreatedAt");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("Shop.DB.Entities.Support.SupportMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("Message");

                    b.Property<int>("Sender")
                        .HasColumnType("integer")
                        .HasColumnName("Sender");

                    b.Property<int>("SupportTicketId")
                        .HasColumnType("integer")
                        .HasColumnName("SupportTicketId");

                    b.HasKey("Id");

                    b.HasIndex("SupportTicketId")
                        .HasDatabaseName("IX_SupportMessages_SupportTicketId");

                    b.ToTable("SupportMessages", (string)null);
                });

            modelBuilder.Entity("Shop.DB.Entities.Support.SupportTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("GuestEmail")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("GuestEmail");

                    b.Property<string>("GuestPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("GuestPhone");

                    b.Property<int?>("OrderId")
                        .HasColumnType("integer")
                        .HasColumnName("OrderId");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("Status");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("Topic");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("IX_SupportTickets_OrderId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_SupportTickets_UserId");

                    b.ToTable("SupportTickets", null, t =>
                        {
                            t.HasCheckConstraint("CK_SupportTicket_Contact", "(\"UserId\" IS NOT NULL) OR (\"GuestEmail\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Shop.DB.Entities.Wishlists.Wishlist", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("UserId");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("ProductId");

                    b.HasKey("UserId", "ProductId");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("IX_Wishlists_ProductId");

                    b.HasIndex("UserId", "ProductId")
                        .IsUnique()
                        .HasDatabaseName("IX_Wishlists_UserId_ProductId");

                    b.ToTable("Wishlists", (string)null);
                });

            modelBuilder.Entity("Shop.DB.Entities.Carts.Cart", b =>
                {
                    b.HasOne("Shop.DB.Entities.Identity.User", "User")
                        .WithOne("Cart")
                        .HasForeignKey("Shop.DB.Entities.Carts.Cart", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Carts_Users_UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Shop.DB.Entities.Carts.CartItem", b =>
                {
                    b.HasOne("Shop.DB.Entities.Carts.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CartItems_Carts_CartId");

                    b.HasOne("Shop.DB.Entities.Catalog.Products.ProductVariant", "ProductVariant")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_CartItems_ProductVariants_ProductVariantId");

                    b.Navigation("Cart");

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("Shop.DB.Entities.Catalog.Category", b =>
                {
                    b.HasOne("Shop.DB.Entities.Catalog.Category", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Categories_Categories_ParentCategoryId");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("Shop.DB.Entities.Catalog.Products.Attributes.ProductAttributeLink", b =>
                {
                    b.HasOne("Shop.DB.Entities.Catalog.Products.Attributes.ProductAttributeValue", "ProductAttributeValue")
                        .WithMany("AttributeLinks")
                        .HasForeignKey("ProductAttributeValueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ProductAttributeLinks_ProductAttributeValues_ProductAttribu~");

                    b.HasOne("Shop.DB.Entities.Catalog.Products.Product", "Product")
                        .WithMany("AttributeLinks")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ProductAttributeLinks_Products_ProductId");

                    b.Navigation("Product");

                    b.Navigation("ProductAttributeValue");
                });

            modelBuilder.Entity("Shop.DB.Entities.Catalog.Products.Attributes.ProductAttributeValue", b =>
                {
                    b.HasOne("Shop.DB.Entities.Catalog.Products.Attributes.ProductAttribute", "ProductAttribute")
                        .WithMany("Values")
                        .HasForeignKey("ProductAttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ProductAttributeValues_ProductAttributes_ProductAttributeId");

                    b.Navigation("ProductAttribute");
                });

            modelBuilder.Entity("Shop.DB.Entities.Catalog.Products.Images.ProductImage", b =>
                {
                    b.HasOne("Shop.DB.Entities.Catalog.Products.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ProductImages_Products_ProductId");

                    b.HasOne("Shop.DB.Entities.Catalog.Products.Options.ProductOptionValue", "ProductOptionValue")
                        .WithMany("Images")
                        .HasForeignKey("ProductOptionValueId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_ProductImages_ProductOptionValues_ProductOptionValueId");

                    b.Navigation("Product");

                    b.Navigation("ProductOptionValue");
                });

            modelBuilder.Entity("Shop.DB.Entities.Catalog.Products.Options.ProductOptionLink", b =>
                {
                    b.HasOne("Shop.DB.Entities.Catalog.Products.Product", "Product")
                        .WithMany("OptionLinks")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ProductOptionLinks_Products_ProductId");

                    b.HasOne("Shop.DB.Entities.Catalog.Products.Options.ProductOptionValue", "ProductOptionValue")
                        .WithMany("OptionLinks")
                        .HasForeignKey("ProductOptionValueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ProductOptionLinks_ProductOptionValues_ProductOptionValueId");

                    b.Navigation("Product");

                    b.Navigation("ProductOptionValue");
                });

            modelBuilder.Entity("Shop.DB.Entities.Catalog.Products.Options.ProductOptionValue", b =>
                {
                    b.HasOne("Shop.DB.Entities.Catalog.Products.Options.ProductOption", "ProductOption")
                        .WithMany("Values")
                        .HasForeignKey("ProductOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ProductOptionValues_ProductOptions_ProductOptionId");

                    b.Navigation("ProductOption");
                });

            modelBuilder.Entity("Shop.DB.Entities.Catalog.Products.Product", b =>
                {
                    b.HasOne("Shop.DB.Entities.Catalog.Products.ProductVariant", "CatalogVariant")
                        .WithMany("CatalogForProducts")
                        .HasForeignKey("CatalogVariantId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Products_ProductVariants_CatalogVariantId");

                    b.HasOne("Shop.DB.Entities.Catalog.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Products_Categories_CategoryId");

                    b.Navigation("CatalogVariant");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Shop.DB.Entities.Catalog.Products.ProductVariant", b =>
                {
                    b.HasOne("Shop.DB.Entities.Catalog.Products.Product", "Product")
                        .WithMany("Variants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ProductVariants_Products_ProductId");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Shop.DB.Entities.Catalog.Products.VariantOptionLink", b =>
                {
                    b.HasOne("Shop.DB.Entities.Catalog.Products.Options.ProductOptionLink", "ProductOptionLink")
                        .WithMany("VariantOptionLinks")
                        .HasForeignKey("ProductOptionLinkId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_VariantOptionLinks_ProductOptionLinks_ProductOptionLinkId");

                    b.HasOne("Shop.DB.Entities.Catalog.Products.Options.ProductOptionValue", "ProductOptionValue")
                        .WithMany("VariantOptionLinks")
                        .HasForeignKey("ProductOptionValueId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_VariantOptionLinks_ProductOptionValues_ProductOptionValueId");

                    b.HasOne("Shop.DB.Entities.Catalog.Products.ProductVariant", "ProductVariant")
                        .WithMany("VariantOptionLinks")
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_VariantOptionLinks_ProductVariants_ProductVariantId");

                    b.Navigation("ProductOptionLink");

                    b.Navigation("ProductOptionValue");

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("Shop.DB.Entities.Discounts.Discount", b =>
                {
                    b.HasOne("Shop.DB.Entities.Catalog.Category", "Category")
                        .WithMany("Discounts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Discounts_Categories_CategoryId");

                    b.HasOne("Shop.DB.Entities.Catalog.Products.Product", "Product")
                        .WithMany("Discounts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Discounts_Products_ProductId");

                    b.HasOne("Shop.DB.Entities.Catalog.Products.ProductVariant", "ProductVariant")
                        .WithMany("Discounts")
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Discounts_ProductVariants_ProductVariantId");

                    b.HasOne("Shop.DB.Entities.Discounts.DiscountType", "DiscountType")
                        .WithMany("Discounts")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Discounts_DiscountTypes_TypeId");

                    b.Navigation("Category");

                    b.Navigation("DiscountType");

                    b.Navigation("Product");

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("Shop.DB.Entities.Discounts.DiscountProduct", b =>
                {
                    b.HasOne("Shop.DB.Entities.Discounts.Discount", "Discount")
                        .WithMany("DiscountProducts")
                        .HasForeignKey("DiscountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DiscountProducts_Discounts_DiscountId");

                    b.HasOne("Shop.DB.Entities.Catalog.Products.Product", "Product")
                        .WithMany("DiscountProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DiscountProducts_Products_ProductId");

                    b.Navigation("Discount");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Shop.DB.Entities.Identity.CustomerProfile", b =>
                {
                    b.HasOne("Shop.DB.Entities.Identity.User", "User")
                        .WithOne("CustomerProfile")
                        .HasForeignKey("Shop.DB.Entities.Identity.CustomerProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CustomerProfiles_Users_UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Shop.DB.Entities.Identity.PersonnelProfile", b =>
                {
                    b.HasOne("Shop.DB.Entities.Identity.User", "User")
                        .WithOne("PersonnelProfile")
                        .HasForeignKey("Shop.DB.Entities.Identity.PersonnelProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PersonnelProfiles_Users_UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Shop.DB.Entities.Identity.User", b =>
                {
                    b.HasOne("Shop.DB.Entities.Identity.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Users_Roles_RoleId");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Shop.DB.Entities.Orders.Order", b =>
                {
                    b.HasOne("Shop.DB.Entities.Identity.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Orders_Users_UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Shop.DB.Entities.Orders.OrderItem", b =>
                {
                    b.HasOne("Shop.DB.Entities.Orders.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_OrderItems_Orders_OrderId");

                    b.HasOne("Shop.DB.Entities.Catalog.Products.ProductVariant", "ProductVariant")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_OrderItems_ProductVariants_ProductVariantId");

                    b.Navigation("Order");

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("Shop.DB.Entities.Payments.Payment", b =>
                {
                    b.HasOne("Shop.DB.Entities.Orders.Order", "Order")
                        .WithMany("Payments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Payments_Orders_OrderId");

                    b.HasOne("Shop.DB.Entities.Payments.Provider", "Provider")
                        .WithMany("Payments")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Payments_Providers_ProviderId");

                    b.Navigation("Order");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("Shop.DB.Entities.Reviews.Review", b =>
                {
                    b.HasOne("Shop.DB.Entities.Orders.Order", "Order")
                        .WithMany("Reviews")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_Reviews_Orders_OrderId");

                    b.HasOne("Shop.DB.Entities.Catalog.Products.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Reviews_Products_ProductId");

                    b.HasOne("Shop.DB.Entities.Identity.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Reviews_Users_UserId");

                    b.Navigation("Order");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Shop.DB.Entities.Support.Notification", b =>
                {
                    b.HasOne("Shop.DB.Entities.Identity.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Notifications_Users_UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Shop.DB.Entities.Support.SupportMessage", b =>
                {
                    b.HasOne("Shop.DB.Entities.Support.SupportTicket", "SupportTicket")
                        .WithMany("Messages")
                        .HasForeignKey("SupportTicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SupportMessages_SupportTickets_SupportTicketId");

                    b.Navigation("SupportTicket");
                });

            modelBuilder.Entity("Shop.DB.Entities.Support.SupportTicket", b =>
                {
                    b.HasOne("Shop.DB.Entities.Orders.Order", "Order")
                        .WithMany("SupportTickets")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_SupportTickets_Orders_OrderId");

                    b.HasOne("Shop.DB.Entities.Identity.User", "User")
                        .WithMany("SupportTickets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_SupportTickets_Users_UserId");

                    b.Navigation("Order");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Shop.DB.Entities.Wishlists.Wishlist", b =>
                {
                    b.HasOne("Shop.DB.Entities.Catalog.Products.Product", "Product")
                        .WithMany("Wishlists")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Wishlists_Products_ProductId");

                    b.HasOne("Shop.DB.Entities.Identity.User", "User")
                        .WithMany("Wishlists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Wishlists_Users_UserId");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Shop.DB.Entities.Carts.Cart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Shop.DB.Entities.Catalog.Category", b =>
                {
                    b.Navigation("Discounts");

                    b.Navigation("Products");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("Shop.DB.Entities.Catalog.Products.Attributes.ProductAttribute", b =>
                {
                    b.Navigation("Values");
                });

            modelBuilder.Entity("Shop.DB.Entities.Catalog.Products.Attributes.ProductAttributeValue", b =>
                {
                    b.Navigation("AttributeLinks");
                });

            modelBuilder.Entity("Shop.DB.Entities.Catalog.Products.Options.ProductOption", b =>
                {
                    b.Navigation("Values");
                });

            modelBuilder.Entity("Shop.DB.Entities.Catalog.Products.Options.ProductOptionLink", b =>
                {
                    b.Navigation("VariantOptionLinks");
                });

            modelBuilder.Entity("Shop.DB.Entities.Catalog.Products.Options.ProductOptionValue", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("OptionLinks");

                    b.Navigation("VariantOptionLinks");
                });

            modelBuilder.Entity("Shop.DB.Entities.Catalog.Products.Product", b =>
                {
                    b.Navigation("AttributeLinks");

                    b.Navigation("DiscountProducts");

                    b.Navigation("Discounts");

                    b.Navigation("Images");

                    b.Navigation("OptionLinks");

                    b.Navigation("Reviews");

                    b.Navigation("Variants");

                    b.Navigation("Wishlists");
                });

            modelBuilder.Entity("Shop.DB.Entities.Catalog.Products.ProductVariant", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("CatalogForProducts");

                    b.Navigation("Discounts");

                    b.Navigation("OrderItems");

                    b.Navigation("VariantOptionLinks");
                });

            modelBuilder.Entity("Shop.DB.Entities.Discounts.Discount", b =>
                {
                    b.Navigation("DiscountProducts");
                });

            modelBuilder.Entity("Shop.DB.Entities.Discounts.DiscountType", b =>
                {
                    b.Navigation("Discounts");
                });

            modelBuilder.Entity("Shop.DB.Entities.Identity.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Shop.DB.Entities.Identity.User", b =>
                {
                    b.Navigation("Cart");

                    b.Navigation("CustomerProfile");

                    b.Navigation("Notifications");

                    b.Navigation("Orders");

                    b.Navigation("PersonnelProfile");

                    b.Navigation("Reviews");

                    b.Navigation("SupportTickets");

                    b.Navigation("Wishlists");
                });

            modelBuilder.Entity("Shop.DB.Entities.Orders.Order", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Payments");

                    b.Navigation("Reviews");

                    b.Navigation("SupportTickets");
                });

            modelBuilder.Entity("Shop.DB.Entities.Payments.Provider", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Shop.DB.Entities.Support.SupportTicket", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
